name: Test Workflow
on: workflow_call

jobs:
  quick_test:
    name: Quickly Test managed Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  quick_test_two:
    name: Quickly Test managed Workflows
    runs-on: ubuntu-latest
    needs: quick_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
