name: Test Workflow
on: workflow_call

jobs:
  quick_test:
    name: Quickly Test managed Workflows
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: https://www.google.com
    steps:
      - uses: ./.github/workflows/checkout.yml
